// export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as SignIn} from './SignIn';
export { default as SignUp} from './SignUp';
export { default as DevSignIn} from './DevSignIn';
export { default as DevSignUp} from './DevSignUp';
export { default as Developer} from './Developer';
// export { default as Icons } from './Icons';
// export { default as NotFound } from './NotFound';
// export { default as ProductList } from './ProductList';
// export { default as Settings } from './Settings';
// export { default as SignIn } from './SignIn';
// export { default as SignUp } from './SignUp';
// export { default as Typography } from './Typography';
// export { default as UserList } from './UserList';
