version: '3'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data:/data/db


  mongo_seed:
    image: mongo:4.2
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh