version: '3'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-volume:/data/db
  
  mongo-seed:
    image: fvilers/mongo-seed
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./data:/data
    command:
      "mongoimport -d MLAI -c 'users' --type json --file /data/users.json"
