version: '3'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-volume:/data/db

  
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb

